[package]
name = "ivmlite-bench"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ivmlite-test = { path = "../ivmlite-test" }
ivmlite-workload = { path = "../ivmlite-workload" }
rusqlite = { workspace = true, features = ["load_extension"] }
